# Generated by Django 4.0.1 on 2022-02-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='isarchive',
            field=models.BooleanField(default=False),
        ),
    ]
