# Generated by Django 4.0.1 on 2022-02-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_note_isarchive'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.JSONField()),
            ],
        ),
    ]
