# Generated by Django 4.0.1 on 2022-02-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_pinqueue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinqueue',
            name='queue',
            field=models.JSONField(default=''),
        ),
    ]
