# Generated by Django 4.0.1 on 2022-02-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_alter_pinqueue_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='islocked',
            field=models.BooleanField(default=False),
        ),
    ]
